import {
  Bug,
  Dark,
  Dragon,
  Electric,
  Fairy,
  Fighting,
  Fire,
  Flying,
  Ghost,
  Grass,
  Ground,
  Ice,
  Normal,
  Poison,
  Psychic,
  Rock,
  Steel,
  Water,
} from '../svgs';

export const type = {
  interThin: 'Inter-Thin',
  interLight: 'Inter-Light',
  interRegular: 'Inter-Regular',
  interMedium: 'Inter-Medium',
  interSemiBold: 'Inter-SemiBold',
  interBold: 'Inter-Bold',
  interBlack: 'Inter-Black',
  interExtraBold: 'Inter-ExtraBold',
  interExtraLight: 'Inter-ExtraLight',
};

// export const POKEMON_TYPE_COLOR = {
//   bug: '#E3D5B9',
//   dark: '#6F6E78',
//   dragon: '#97B3E6',
//   electric: '#F9E8B3',
//   fairy: '#FCEAFF',
//   fighting: '#EAE6DF',
//   fire: '#FFDCBD',
//   flying: '#ACC1EC',
//   ghost: '#C3B9DF',
//   grass: '#BDE8B0',
//   ground: '#F4E7DA',
//   ice: '#E7F6FE',
//   normal: '#F0F0F0',
//   poison: '#D6C2D3',
//   psychic: '#FFCCE8',
//   rock: '#E5D6C7',
//   steel: '#E6EBEE',
//   water: '#B6DAFB',
// };

export const POKEMON_TYPE_COLOR = {
  bug: '#83C300',
  dark: '#5B5466',
  dragon: '#006FC9',
  electric: '#FBD100',
  fairy: '#FB89EB',
  fighting: '#E0306A',
  fire: '#FF9741',
  flying: '#89AAE3',
  ghost: '#4C6AB2',
  grass: '#38BF4B',
  ground: '#E87236',
  ice: '#4CD1C0',
  normal: '#919AA2',
  poison: '#B567CE',
  psychic: '#FF6675',
  rock: '#C8B686',
  steel: '#5A8EA2',
  water: '#3692DC',
};

export const POKEMON_TYPE_BACKGROUND = {
  bug: '#8CB230',
  dark: '#58575F',
  dragon: '#0F6AC0',
  electric: '#EED535',
  fairy: '#ED6EC7',
  fighting: '#D04164',
  fire: '#FD7D24',
  flying: '#748FC9',
  ghost: '#556AAE',
  grass: '#62B957',
  ground: '#DD7748',
  ice: '#61CEC0',
  normal: '#9DA0AA',
  poison: '#A552CC',
  psychic: '#EA5D60',
  rock: '#BAAB82',
  steel: '#417D9A',
  water: '#417D9A',
};

export const POKEMON_TYPE_ICON = {
  bug: Bug,
  dark: Dark,
  dragon: Dragon,
  electric: Electric,
  fairy: Fairy,
  fighting: Fighting,
  fire: Fire,
  flying: Flying,
  ghost: Ghost,
  grass: Grass,
  ground: Ground,
  ice: Ice,
  normal: Normal,
  poison: Poison,
  psychic: Psychic,
  rock: Rock,
  steel: Steel,
  water: Water,
};
